<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>

        <TargetFramework>net10.0</TargetFramework>

        <Title>QuikGraph.Graphviz.Tests</Title>

        <Version>1.0.0</Version>
        <AssemblyVersion>1.0.0</AssemblyVersion>
        <FileVersion>1.0.0</FileVersion>

        <Copyright>Copyright © 2020</Copyright>
        <Description>Tests for QuikGraph.Graphviz library.</Description>
    </PropertyGroup>

    <!-- Dependencies -->
    <!-- Externals -->
    <ItemGroup>
        <PackageReference Include="HtmlAgilityPack"/>
    </ItemGroup>

    <!-- Shared Projects -->
    <Import Project="..\..\src\QuikGraph.CommonInternals\QuikGraph.CommonInternals.projitems" Label="Shared"/>

    <!-- Projects -->
    <!-- QuikGraph.Graphviz reference -->
    <ItemGroup>
        <ProjectReference Include="..\..\src\QuikGraph.Graphviz\QuikGraph.Graphviz.csproj"/>
    </ItemGroup>
</Project>