<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <AssemblyName>QuikGraph.Benchmarks</AssemblyName>
        <RootNamespace>QuikGraph.Benchmarks</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BenchmarkDotNet"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\QuikGraph\QuikGraph.csproj"/>
    </ItemGroup>
</Project>
