<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>

        <TargetFramework>net10.0</TargetFramework>

        <Title>QuikGraph.Tests</Title>

        <Version>1.0.0</Version>
        <AssemblyVersion>1.0.0</AssemblyVersion>
        <FileVersion>1.0.0</FileVersion>

        <Copyright>Copyright © 2019</Copyright>
        <Description>Tests for QuikGraph library.</Description>
    </PropertyGroup>

    <PropertyGroup Condition="$(DeployBuild)">
        <SignAssembly>true</SignAssembly>
        <AssemblyOriginatorKeyFile>..\..\QuikGraph.snk</AssemblyOriginatorKeyFile>
    </PropertyGroup>
    <ItemGroup>
        <None Include="$(ProjectDir)GraphML\**" CopyToOutputDirectory="PreserveNewest"/>
    </ItemGroup>

    <!-- Dependencies -->
    <!-- Shared Projects -->
    <Import Project="..\QuikGraph.Serialization.Tests.CommonInternals\QuikGraph.Serialization.Tests.CommonInternals.projitems" Label="Shared"/>

    <!-- QuikGraph reference -->
    <ItemGroup>
        <ProjectReference Include="..\..\src\QuikGraph\QuikGraph.csproj"/>
        <ProjectReference Include="..\..\src\QuikGraph.Serialization\QuikGraph.Serialization.csproj"/>
    </ItemGroup>
</Project>