<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>

        <Title>QuikGraph.Data.Tests</Title>

        <Version>1.0.0</Version>
        <AssemblyVersion>1.0.0</AssemblyVersion>
        <FileVersion>1.0.0</FileVersion>

        <Copyright>Copyright © 2020</Copyright>
        <Description>Tests for QuikGraph.Data library.</Description>
    </PropertyGroup>

    <!-- Dependencies -->
    <!-- Shared Projects -->
    <Import Project="..\..\src\QuikGraph.CommonInternals\QuikGraph.CommonInternals.projitems" Label="Shared"/>

    <!-- Projects -->
    <!-- QuikGraph.Data reference -->
    <ItemGroup>
        <ProjectReference Include="..\..\src\QuikGraph.Data\QuikGraph.Data.csproj"/>
    </ItemGroup>
</Project>